package br.gov.pa.prodepa.pae.protocolo.jpapersistenceadapter.entity;
// Generated 18 de mar de 2021 00:52:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProtocoloId generated by hbm2java
 */
@Embeddable
public class ProtocoloEntityId implements java.io.Serializable {

	private short ano;
	private long numeroProtocolo;

	public ProtocoloEntityId() {
	}

	public ProtocoloEntityId(short ano, long numeroProtocolo) {
		this.ano = ano;
		this.numeroProtocolo = numeroProtocolo;
	}

	@Column(name = "ano", nullable = false)
	public short getAno() {
		return this.ano;
	}

	public void setAno(short ano) {
		this.ano = ano;
	}

	@Column(name = "numero_protocolo", nullable = false)
	public long getNumeroProtocolo() {
		return this.numeroProtocolo;
	}

	public void setNumeroProtocolo(long numeroProtocolo) {
		this.numeroProtocolo = numeroProtocolo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProtocoloEntityId))
			return false;
		ProtocoloEntityId castOther = (ProtocoloEntityId) other;

		return (this.getAno() == castOther.getAno()) && (this.getNumeroProtocolo() == castOther.getNumeroProtocolo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAno();
		result = 37 * result + (int) this.getNumeroProtocolo();
		return result;
	}

}
