package br.gov.pa.prodepa.pae.protocolo.jpapersistenceadapter.entity;
// Generated 18 de mar de 2021 00:52:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProtocoloId generated by hbm2java
 */
@Embeddable
public class ProtocoloEntityId implements java.io.Serializable {

	private static final long serialVersionUID = -3646650670049391489L;
	
	private short anoProtocolo;
	private long numeroProtocolo;

	public ProtocoloEntityId() {
	}

	public ProtocoloEntityId(short anoProtocolo, long numeroProtocolo) {
		this.anoProtocolo = anoProtocolo;
		this.numeroProtocolo = numeroProtocolo;
	}

	@Column(name = "ano_protocolo", nullable = false)
	public short getAnoProtocolo() {
		return this.anoProtocolo;
	}

	public void setAnoProtocolo(short anoProtocolo) {
		this.anoProtocolo = anoProtocolo;
	}

	@Column(name = "numero_protocolo", nullable = false)
	public long getNumeroProtocolo() {
		return this.numeroProtocolo;
	}

	public void setNumeroProtocolo(long numeroProtocolo) {
		this.numeroProtocolo = numeroProtocolo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProtocoloEntityId))
			return false;
		ProtocoloEntityId castOther = (ProtocoloEntityId) other;

		return (this.getAnoProtocolo() == castOther.getAnoProtocolo()) && (this.getNumeroProtocolo() == castOther.getNumeroProtocolo());
	}

	public int hashCode() {
		var result = 17;

		result = 37 * result + this.getAnoProtocolo();
		result = 37 * result + (int) this.getNumeroProtocolo();
		return result;
	}

}
