package br.gov.pa.prodepa.pae.protocolo.jpapersistenceadapter.entity;
// Generated 11 de mar de 2021 14:58:24 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SequencialDocumentoId generated by hbm2java
 */
@Embeddable
public class SequencialDocumentoEntityId implements java.io.Serializable {

	private int ano;
	private long especieId;
	private long localizacaoId;

	public SequencialDocumentoEntityId() {
	}

	public SequencialDocumentoEntityId(int ano, long especieId, long localizacaoId) {
		this.ano = ano;
		this.especieId = especieId;
		this.localizacaoId = localizacaoId;
	}

	@Column(name = "ano", nullable = false)
	public int getAno() {
		return this.ano;
	}

	public void setAno(int ano) {
		this.ano = ano;
	}

	@Column(name = "especie_id", nullable = false)
	public long getEspecieId() {
		return this.especieId;
	}

	public void setEspecieId(long especieId) {
		this.especieId = especieId;
	}

	@Column(name = "localizacao_id", nullable = false)
	public long getLocalizacaoId() {
		return this.localizacaoId;
	}

	public void setLocalizacaoId(long localizacaoId) {
		this.localizacaoId = localizacaoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SequencialDocumentoEntityId))
			return false;
		SequencialDocumentoEntityId castOther = (SequencialDocumentoEntityId) other;

		return (this.getAno() == castOther.getAno()) && (this.getEspecieId() == castOther.getEspecieId())
				&& (this.getLocalizacaoId() == castOther.getLocalizacaoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAno();
		result = 37 * result + (int) this.getEspecieId();
		result = 37 * result + (int) this.getLocalizacaoId();
		return result;
	}

}
