package br.gov.pa.prodepa.pae.protocolo.jpapersistenceadapter.entity;
// Generated 11 de mar de 2021 14:58:24 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SequencialDocumento generated by hbm2java
 */
@Entity
@Table(name = "sequencial_documento", schema = "pae")
public class SequencialDocumentoEntity implements java.io.Serializable {

	private static final long serialVersionUID = 2448300484415113641L;
	
	private SequencialDocumentoEntityId id;
	private long sequencial;

	public SequencialDocumentoEntity() {
	}

	public SequencialDocumentoEntity(SequencialDocumentoEntityId id, Long sequencial) {
		this.id = id;
		this.sequencial = sequencial;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ano", column = @Column(name = "ano", nullable = false)),
			@AttributeOverride(name = "especieId", column = @Column(name = "especie_id", nullable = false)),
			@AttributeOverride(name = "localizacaoId", column = @Column(name = "localizacao_id", nullable = false)) })
	public SequencialDocumentoEntityId getId() {
		return this.id;
	}

	public void setId(SequencialDocumentoEntityId id) {
		this.id = id;
	}

	@Column(name = "sequencial", nullable = false)
	public long getSequencial() {
		return this.sequencial;
	}

	public void setSequencial(long sequencial) {
		this.sequencial = sequencial;
	}

}
